services:
  postgres:
    image: postgres:15-alpine
    container_name: example-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: